language: cpp

before_install:
 - curl http://apt.wxwidgets.org/key.asc | sudo apt-key add -
 - yes | sudo add-apt-repository "deb http://apt.wxwidgets.org/ `lsb_release -sc`-wx main"
 - sudo apt-get update
 - sudo apt-get install libwxbase2.8-dev libwxgtk2.8-dev wx2.8-i18n doxygen cmake

install:
 - mkdir build
 - cd build
 - cmake .. && make
 - src/oyun --test
