language: cpp

before_install:
 - yes | sudo add-apt-repository ppa:fransschreuder1/usbpicprog-stable
 - sudo apt-get update
 - sudo apt-get install libwxbase2.9-dev libwxgtk2.9-dev wx2.9-i18n cmake

install:
 - mkdir cmake_build_temp
 - cd cmake_build_temp
 - cmake .. && make
 - src/oyun_test
